# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: stevewa.sh - irate iguana
header_title: S
email: washington.steven@gmail.com
author: Steven Washington
description: >- # this means to ignore newlines until "baseurl:"
  Just a dev doing stuff
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: esaevian
github_username:  washingtonsteven
header_pages:
  - contact.md
  - uses.md
  - about.md
  - posts.md
  - projects.md
collections:
  projects:
    output: true
    layout: project
footer_links:
  - title: Home
    url: /
  - title: Github
    url: https://github.com/washingtonsteven
  - title: Twitter
    url: https://twitter.com/esaevian
  - title: Contact
    url: /contact/
  - title: Feed
    url: /feed.xml
defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: project

# Build settings
markdown: kramdown
# theme: minima
plugins:
  - jekyll-feed

# repository: washingtonsteven/washingtonsteven.github.io

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
